### ISSUE TITLE
Add event page

### ISSUE THREAD

**Issue by alanvardy** [elixirvictoria/elixirvictoria#19]
Can be static for now.

Day, time, topic, links to more information.

Topic is going to be "What do you want from this meetup" or "meet the other Elixirists" etc.

Maybe we can have a little content? It would be nice if we could get someone from AppColony or Pixel Union to say a little bit about how it is used at those companies.

**Comment by SupaMic** [comment]
Working on today

**Comment by alanvardy** [comment]
First meetup is passed and events CRUD is implemented
