### ISSUE TITLE
Deploy site

### ISSUE THREAD

**Issue by alanvardy** [elixirvictoria/elixirvictoria#20]
I will deploy to my personal server on DigitalOcean

**Comment by SupaMic** [comment]
I think the site is ready to deploy and announce! The earlier it's up, then the earlier we can spread the domain name and better chance of reaching more interested people.

We should add a note that the site is under active development and more info to follow but the most important data people need is available now.

**Comment by alanvardy** [comment]
Sounds good! I will get that ball rolling today or tomorrow :)

**Comment by alanvardy** [comment]
PR up.
