### ISSUE TITLE
Ex_check on Windows bug: Can't run mix check

### ISSUE THREAD

**Issue by SupaMic** [elixirvictoria/elixirvictoria#23]
When running `mix check` for tests on Windows we get a terminating error.

```
[error] Task #PID<0.121.0> started from #PID<0.111.0> terminating
** (stop) :eacces
    erlang.erl:2213: :erlang.open_port({:spawn_executable, "c:/Program Files/nodejs/npm.cmd"}, [:stream, :binary, :exit_status, :hide, :use_stdio, :stderr_to_stdout, {:args, ["test"]}, {:cd, "assets"}, {:env, []}])
    lib/ex_check/command.ex:34: anonymous fn/4 in ExCheck.Command.async/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<1.93762643/0 in ExCheck.Command.async/2>
    Args: []
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (ErlangError) Erlang error: :eacces
        erlang.erl:2213: :erlang.open_port({:spawn_executable, "c:/Program Files/nodejs/npm.cmd"}, [:stream, :binary, :exit_status, :hide, :use_stdio, :stderr_to_stdout, {:args, ["test"]}, {:cd, "assets"}, {:env, []}])
        lib/ex_check/command.ex:34: anonymous fn/4 in ExCheck.Command.async/2
        (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

From this post I've narrowed this down to a Windows restriction where Erlang cannot spawn a .cmd filetype as an executable. [Port.open EACCES on Windows](https://elixirforum.com/t/port-open-eacces-on-windows/5442/6)  

The solution is to modify the the executable to be windows shell `cmd.exe` and add `path/npm.cmd` to :args.

We need to modify or create another function clause in the `/deps/ex_check/lib/ex_check/command.ex` `async function` using a `:os.type` to determine if we are on windows.

Since this is an external package I'm not comfortable submitting PRs to them just yet since I'm still in early learning stages so I'll be moving to Ubuntu for further dev.

**Comment by alanvardy** [comment]
Ubuntu is probably the best long term option to be honest, the developer experience with Elixir on Windows is somewhere between bad and awful. I don't fault the Core elixir team for it, apparently they spend more time on Windows tooling than Linux in their releases.

Some recent info here.
[https://elixirforum.com/t/the-elixir-experience-on-windows-is-deteriorating/26538](https://elixirforum.com/t/the-elixir-experience-on-windows-is-deteriorating/26538)

Maybe we can leave a note in the Readme that the we do not recommend using a Windows dev environment. And also on the Website itself.

**Comment by alanvardy** [comment]
In the meantime you can run the following:

`mix format && mix compile --warnings-as-errors && mix test && mix credo --strict && mix cypress.run`

That will get you most of the way.

**Comment by alanvardy** [comment]
Closing as resolved.
