### ISSUE TITLE
Phoenix generators still using old namespace: Elixirvictoria

### ISSUE THREAD

**Issue by SupaMic** [elixirvictoria/elixirvictoria#38]
I used a basic phx.gen.html command and all the files it created used the original namespace Elixirvictoria with lowercase "v" even though every config file was modified in [this commit](https://github.com/elixirvictoria/elixirvictoria/commit/7a838d64494fe837d2fe2b2d989dcadb7f26438e).

![phx_gen_html](https://user-images.githubusercontent.com/970239/73041660-28ead200-3e13-11ea-8da3-bad9dfe5d81d.png)
![context](https://user-images.githubusercontent.com/970239/73041678-36a05780-3e13-11ea-912e-ead14902d13f.png)
![schema](https://user-images.githubusercontent.com/970239/73041687-3ef89280-3e13-11ea-92b4-ab64562ee11a.png)

I found one exception, in [/elixirvictoria/lib/elixirvictoria_web.ex](https://github.com/elixirvictoria/elixirvictoria/blob/399108cafd5c420d36d7eaea0997833dc5e13b8a/lib/elixirvictoria_web.ex#L34), under `def view do` on line 34, the `namespace: Elixirvictoria`.   Also found some docs reference this original application name.  I'll submit a PR for this separately.

When I fix all of these and recompile though I get the same problem with generators even though when I grep the entire codebase I can find no other examples of this name, so I can't figure out where Phoenix is pulling this old app name from.

I can manually edit the module names easily enough but it would be good to find and make this change either in the Repo if Phoenix is pulling it from there or wherever it is.

**Comment by alanvardy** [comment]
I think that phoenix is probably just taking the app name and converting from snake case.

If we name the app :elixir_victoria it may sold the problem. What do you think?

We can also revert back to Elixirvictoria but I just didnt find it legible.

**Comment by alanvardy** [comment]
Take a look at the config here too:
https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Html.html

**Comment by SupaMic** [comment]
I'll test in my branch to see if that works.  Makes sense because when I
used a gen that referenced the ElixirVictoria context it created a folder
elixir_victoria and used module name Elixirvictoria.ElixirVictoria.Event

**Comment by SupaMic** [comment]
Updating with an underscore on the app atoms :elixir_victoria and folder names elixir_victoria & elixir_victoria_web has fixed it.
submitting PR shortly

**Comment by alanvardy** [comment]
You can use the syntax:

Closes #38

In your pull request and it will automatically link this issue to it, and close the issue once your PR is merged.

**Comment by SupaMic** [comment]
good to know
